app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: "@ApiBundle/Resources/config/routes.yml"
    type:     rest
    prefix:   /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routes.yml"
    prefix:   /api/doc
