services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    mailer.locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: true
        tags:
            - { name: container.service_locator }
        arguments:
            -
               default: '@AppBundle\Mailer\DefaultMailer'

    AppBundle\Mailer\:
        resource: '../../src/AppBundle/Mailer/*'
        public: true

    AppBundle\Mailer\MailerController:
        public: true
        arguments:
            - '@mailer.locator'

    AppBundle\Mailer\DefaultMailer:
        arguments:
            - '%kernel.project_dir%'

