<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function findAllPendingEmails(int $limit)
    {
        $limit = ($limit === 0) ? null : $limit;

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from(Email::class, 'm')
            ->where("m.status = 'pending'")
            ->orderBy("m.priority", "DESC")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
