<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
    public function findAllPendingEmails(int $limit = 10)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from(Mail::class, 'm')
            ->where("m.status = 'pending'")
            ->orderBy("m.priority", "DESC")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
